# Generated by Django 5.2.4 on 2025-07-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_punlished',
            new_name='date_posted',
        ),
    ]
